# Generated by Django 3.0.7 on 2023-06-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='reg_num',
            new_name='regnum',
        ),
    ]
