# Generated by Django 3.0.7 on 2023-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_dashboard', '0002_auto_20230628_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
